---
title: "stains_study"
author: "Tomas Sladecek"
date: "7/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstudioapi)

setwd(dirname(getActiveDocumentContext()$path))
```

```{r}
chrStains <- read_tsv("../../results/chromosome_stains_ISV.tsv")
chrStains$stain <- factor(chrStains$stain, 
                          levels=c("gneg", "gpos25", "gpos50", "gpos75", "gpos100", "acen", "gvar", "stalk"))

chrStains <- chrStains %>% 
  filter(stain %in% c("gneg", "gpos25", "gpos50", "gpos75", "gpos100")) %>% 
  pivot_longer(c("ISV_loss", "ISV_gain"), names_to = "cnv_type", names_prefix = "ISV_", values_to="ISV") %>%
  arrange(cnv_type)

chrStains$cnv_type <- factor(chrStains$cnv_type, levels=c("gain", "loss"))
chrStains
```

```{r}
chrStains %>% 
  ggplot(aes(x=stain, y=ISV)) + 
    geom_boxplot() + 
    facet_wrap(~cnv_type, nrow = 2)


chrStains %>% 
  ggplot(aes(ISV)) + 
    geom_histogram(binwidth = 0.025) +
    facet_wrap(cnv_type~stain, nrow=2)
```

# ANOVA

### Calculate variances of groups

```{r}
chrStains %>%
  group_by(cnv_type, stain) %>% 
  summarise(mean = mean(ISV), var = var(ISV), n = length(ISV))
```

```{r}
gain_lm <- lm(ISV ~ stain, chrStains %>% filter(cnv_type == "gain"))
loss_lm <- lm(ISV ~ stain, chrStains %>% filter(cnv_type == "loss"))

summary(gain_lm)
summary(loss_lm)
```

```{r}
gain_kw <- kruskal.test(ISV ~ stain, chrStains %>% filter(cnv_type == "gain"))
loss_kw <- kruskal.test(ISV ~ stain, chrStains %>% filter(cnv_type == "loss"))

gain_kw
loss_kw
```

